version: '3.6'
services:
  postgres:
    container_name: postgres-todo-app
    image: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - todo-app-development:/var/lib/postgresql/data

volumes:
  todo-app-development:
networks:
  dev:
    driver: bridge
